import { prisma } from "@/libs/prisma";
import { RedisProvider } from "@/libs/RedisProvider";
import { Prisma } from "@prisma/client";

/**
 * Defines the shape of an Employee object, including related data.
 * This type is generated by Prisma based on the `include` query, ensuring type safety.
 */
export type Employee = Prisma.EmployeeGetPayload<{
  include: {
    user: {
      select: {
        id: true;
        username: true;
        email: true;
      };
    };
    reportManager: true;
    assignMembers: true;
    leaveBalances: true;
    EmployeeLatestIncrement: true;
    leavesApplied: true;
    leavesActioned: true;
  };
}>;

/**
 * Fetch all employees from Redis cache if available,
 * otherwise fetch from the database and cache the result for subsequent requests.
 * @returns {Promise<Employee[]>} A promise that resolves to an array of employee objects.
 */
export const getEmployees = async (): Promise<Employee[]> => {
  const redis = RedisProvider.getInstance();
  try {
    let employees = await redis.getList<Employee>("employees:list");
    // If the Employees Exits, it's a cache hit.
    if (employees) {
      console.log("Cache HIT ✅: Employees from Redis");
      // Retrieve the full list of employees from Redis.

      return employees;
    }

    // If the cache is empty (cache miss), fetch data from the database.
    console.log("Cache MISS ❌: Fetching employees from DB...");

    // Use Prisma client to fetch all employees and include their related data.
    employees = await prisma.employee.findMany({
      include: {
        user: {
          select: {
            id: true,
            username: true,
            email: true,
          },
        },
        reportManager: true,
        assignMembers: {
          include: {
            user: {
              select: {
                id: true,
                username: true,
                email: true,
                dateOfBirth: true,
                gender: true,
                createdAt: true,
              },
            },
          },
        },
        leaveBalances: true,
        EmployeeLatestIncrement: true,
        leavesApplied: true,
        leavesActioned: {},
      },
    });

    // After fetching from the DB, store the result in the Redis cache for future requests.
    console.log("Employees saved to Redis cache 🔐");
    await redis.setList("employees:list", employees);

    return employees;
  } catch (error: any) {
    console.error("Error getting employees:", error);
    // Return an empty array in case of an error to prevent downstream issues.
    return [] as Employee[];
  }
};
